const articles = [
  {
    imgSrc: "images/image1.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image2.png",
    title: "Python for the Absolute beginners",
    text: "Python is the most popular programming language out there and it is used for so many different industries.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image3.png",
    title: "Docker from Zero to Hero",
    text: "Learn what is Docker and  how Docker is used in the whole software development process.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image4.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image5.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image6.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image7.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image8.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image9.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image1.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image2.png",
    title: "Python for the Absolute beginners",
    text: "Python is the most popular programming language out there and it is used for so many different industries.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image3.png",
    title: "Docker from Zero to Hero",
    text: "Learn what is Docker and  how Docker is used in the whole software development process.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image4.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
  {
    imgSrc: "images/image5.png",
    title: "Build continuous integration pipelines with GitHub Actions",
    text: "GitHub actions provide a really powerful way to integrate continuous integration and delivery into your applications.",
    date: "June 24, 2022",
    category: "DevOps",
  },
];

const categories = [
  "JavaScript",
  "DevOps",
  "Cloud",
  "Terraform",
  "Architecture",
  "Scalability",
  "Explainers",
];

export { articles, categories };
